image: node:16

stages:
  - install
  - test
  - build
  - deploy

# Install all dependencies and cache them.
install_dependencies:
  stage: install
  only:
    - master
    - stage
  script:
    - npm i
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

# Check code standards.
lint:
  stage: test
  only:
    - master
    - stage
  script: npm run lint
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

# Build project for prod deployment + store artifacts.
build:
  stage: build
  only:
    - master
  artifacts:
    name: build_stage
    expire_in: 1 hour
    when: on_success
    paths:
      - dist/
  script: npm run build -- --prod
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

# Deploy on self-hosted environment.
deploy_dev:
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass rsync
    - 'which ssh-agent || (apt-get install -y -qq openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - npm i
  script:
    - npm run build -- --prod
    - rsync -e "ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=yes" -avzr --delete dist/admin-dashboard/* reliefapps@92.243.25.191:/var/www/html/assessment-tool/admin-dashboard
  only:
    - master

# Build project for dev deployment + store artifacts.
build:
  stage: build
  only:
    - stage
  artifacts:
    name: build_stage
    expire_in: 1 hour
    when: on_success
    paths:
      - dist/
  script: npm run build:azure
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

# Deploy on azure environment.
deploy_azure:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  only:
    - stage
  before_script:
    - az config set extension.use_dynamic_install=yes_without_prompt
  script:
    - az storage remove -c '$web' --recursive --account-name loassessmenttooladmin --account-key $ACCOUNT_KEY
    - az storage azcopy blob upload -c '$web' -s 'dist/admin-dashboard/*' --recursive --account-name loassessmenttooladmin --account-key $ACCOUNT_KEY
